### ISSUE TITLE
Todo list 

### ISSUE THREAD

**Issue by GillesDeBorger** [GillesDeBorger/PSE#1]
- [ ]
- [ ]
- [ ]

**Comment by GillesDeBorger** [comment]
specificaties: 
- [ ] 1.1a - stad inlezen (met Winkels) 
- [ ] 1.1b - stad inlezen (met Ziekenhuizen en/of Politieburea's) 
- [ ] 1.2   - voertuigen inlezen (brandweerwagens)
- [ ] 1.2a - voertuigen inlezen (ziekenwagens en/of politiewagens) 
- [ ] 2.1   - simpele uitvoer (met brandweerkazerne) -->teksbestand 
- [ ] 2.1a - simpele uitvoer (met winkels)  --> teksbestand 
- [ ] 2.1b - simpele uitvoer (met ziekenhuizen en of politiebureaus) -->teksbestand 
- [ ] 2.2   - simpele graphische impressie --> ASCII voorstelling 
- [ ] 2.2a - simpele graphische impressie (voor alle wagens en gebouwen) -->ASCII voorselling
- [ ] 3.1a - brand breekt uit (in alle gebouwen) 
- [ ] 3.5   - brand verspreid zich (startBurn())
- [ ] 3.6   - winkels worden overvallen (startRobbery())
- [ ] 3.7   - politie wagen rijdt uit voor overval 
- [ ] 3.11 - gebouwen repareren zichzelf 
- [ ] 4.1   - simpele UI 

extras: 
- [ ]  simulatie klasse
